# A discord authentication token
token: 'fakeToken'

# What environment to start the bot in
environment: 'production'

# Sentry DSN
sentryDsn: 'fakeDsn'

# The PostgreSQL credentials to connect with
dbUri: 'postgres://cardinal:password@database/cardinal'

# The prefix the bot should use
prefix: '!'

# An comma-separated list of bot owners
botOwners: '1234567890123456'
